#!/usr/bin/env bash
# bootstrap.sh — Bootstrap for fresh Arch Linux
# git clone https://github.com/SkogAI/bootstrap && cd bootstrap && ./bootstrap.sh
set -euo pipefail

log() { printf '\033[0;32m[+]\033[0m %s\n' "$*"; }

# Install minimum deps
log "Installing base packages..."
sudo pacman -S --needed --noconfirm github-cli uv git

# Fix locale (Arch ships with none generated by default)
log "Fixing locale..."
./locale.sh

# Setup ansible via uv
log "Setting up ansible..."
uv tool install ansible-core --force
export PATH="$HOME/.local/bin:$PATH"

# Auth gh (skips if already logged in)
./gh-auth.sh

# Install ansible collections and run playbook
log "Running ansible..."
ansible-galaxy collection install -r .requirements.yml --force
ansible-playbook playbooks/bootstrap.yml --ask-become-pass
