---
# Install regular + AUR packages using yay, as aur_builder (no root needed)

- name: Install packages using yay
  kewlfft.aur.aur:
    name: "{{ (packages | default([])) + (aur_packages | default([])) }}"
    use: yay
    state: present
  become: true
  become_user: aur_builder
  when: ((packages | default([])) + (aur_packages | default([]))) | length > 0
