---
# Ensure user groups are configured first
- name: Configure user groups
  ansible.builtin.include_tasks: user_groups.yml

# setup aur user
- name: Setup AUR builder user
  ansible.builtin.include_tasks: aur_user.yml

- name: Install yay AUR helper
  ansible.builtin.include_tasks: aur_install_yay.yml
